language: node_js
node_js:
    - 11
    - 10
    - 8
script: npm run test && npm run lint
cache:
    node: true
branches:
    only:
        - master
        - /^greenkeeper/.*$/
dist: trusty
before_install: cd server
