language: node_js
node_js:
    - 11
    - 10
    - 8
script: cd server && npm run test:coverage && npm run lint
cache:
    node: true
branches:
    only:
        - master
dist: trusty
install: cd server && npm install
