name: Run all tests on PR

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - main
      - alpha
      - beta
      - next

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
